name: Deploy MERN + Vite App to GitHub Pages

on:
  push:
    branches: ["main"]  # or "master" if that's your default
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # Adjust to your preferred Node version

      # Install dependencies (both backend & frontend)
      - name: Install Backend Dependencies
        run: |
          cd backend  # Assuming backend folder
          npm install

      - name: Install Frontend Dependencies
        run: |
          cd frontend  # Assuming frontend folder with Vite React app
          npm install

      # Build Frontend (Vite build outputs static files)
      - name: Build Frontend
        run: |
          cd frontend
          npm run build

      # Upload built frontend (for GitHub Pages)
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: frontend/dist  # Vite build output directory

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

